name: BlockProtection
main: roi611\blockprotection\Main
version: 1.3.1
api:
- 4.0.0
- 5.0.0-ALPHA1
load: POSTWORLD
author: roi611
description: ブロックを保護を保護します

commands:
  get: 
    description: 保護用アイテムを取得します
    usage: /get
    permission: "get.command"

permissions:
  get.command:
    default: op
  